
<h1> DS200A Computer Vision Assignment</h1>

<h2>  Part Three: Classifier training and performance assessment. </h2>	

In [1]:
#Import anything you need here
# !pip install opencv-python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib
import skimage
from PIL import Image

from skimage import data
from skimage import io
import os
from skimage.io import imread_collection
from skimage.io import imread
import zipfile
import matplotlib.image as mpimg
import cv2

from sklearn.cluster import KMeans
from skimage import measure
import numpy as np
import imageio
import warnings
import matplotlib.cbook

from PIL import Image
from fractions import Fraction
import seaborn as sns
from sklearn.model_selection import cross_validate

In [2]:
from sklearn.model_selection import train_test_split

def train_test_split_2(df):
    train, val = train_test_split(df, test_size=0.1, random_state=42)
    return df
#Split the data into a training set, and test set 
def accuracy(pred, actual):
    
    return 0
# Calculate the accuracy percentage of the predicted values

<h3>  Train models using all of the following methods below. Be sure to drop the actual image column, and the encoding</h3>	Take note of the differences in accuracy, and methods.


In [3]:
feature_frame = pd.read_pickle('feature_frame.pk1')

In [4]:
train, val = train_test_split(feature_frame, test_size=0.1, random_state=42)

Logistic Regression

In [5]:
train.columns

Index(['Pictures', 'Encoding', 'Images', 'ft0', 'ft1', 'ft2', 'ft3', 'ft4',
       'ft9', 'ft13', 'ft14'],
      dtype='object')

In [6]:
train[['ft0', 'ft1', 'ft2', 'ft3', 'ft4', 'ft9', 'ft13', ]].head()

ft0         ft1       ft2         ft3         ft4      ft9  \
1091  (1600, 1200)  141.865891  1.333333  145.102468  141.365438  1920000   
1150    (695, 421)   99.639662  1.650831   76.053555   99.706697   292595   
1467    (480, 313)  171.792632  1.533546  212.401411  203.883533   150240   
526     (200, 273)  140.572766  0.732601  150.120531  150.788498    54600   
1314   (698, 1001)  167.074393  0.697303  174.355816  161.909792   698698   

           ft13  
1091  60.757454  
1150  88.843627  
1467  27.130666  
526   60.407517  
1314  53.831960

In [7]:
X_train = train[['ft1', 'ft2', 'ft3', 'ft4', 'ft9', 'ft13']]
Y_train = train[['Encoding']]

In [8]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression() # SOLUTION
model.fit(X_train, Y_train) # SOLUTION

training_accuracy = model.score(X_train, Y_train) # SOLUTION
print("Training Accuracy: ", training_accuracy)

/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Training Accuracy:  0.2985185185185185


K-nearest Neighbors

In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(X_train, Y_train['Encoding'])


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [10]:
knn_model.score(X_train, Y_train["Encoding"], sample_weight=None)

0.5

Classification Tree

In [11]:
from sklearn import tree
clf_model = tree.DecisionTreeClassifier(max_depth=8, random_state=42)
clf_model = clf_model.fit(X_train, Y_train['Encoding'])

In [12]:
clf_model.score(X_train, Y_train["Encoding"])

0.43333333333333335

Random Forest

In [13]:
from sklearn import ensemble

In [14]:
random_forest_model = ensemble.RandomForestClassifier(n_estimators=10, random_state=42) # SOLUTION
random_forest_model.fit(X_train, Y_train['Encoding']) # SOLUTION

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [15]:
rf_train_accuracy = random_forest_model.score(X_train, Y_train)
rf_train_accuracy

0.9925925925925926

Support Vector Machine

In [16]:
from sklearn import svm
np.array(Y_train["Encoding"])

array([14, 14, 19, ..., 11, 19, 14])

In [17]:
svm_model = svm.SVC(decision_function_shape='ovo')
svm_model.fit(X_train, Y_train)

/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [18]:
svm_model.score(X_train, Y_train['Encoding'])

1.0

<h4> Cross Validation <h4> 

In [19]:
cv_results_random_f = cross_validate(random_forest_model, X_train, Y_train["Encoding"], cv=5)
cv_results_random_f

{'fit_time': array([0.05514789, 0.04544306, 0.04335093, 0.04030895, 0.042454  ]),
 'score_time': array([0.00406599, 0.00406194, 0.00365114, 0.00293922, 0.00338578]),
 'test_score': array([0.32014388, 0.32720588, 0.32713755, 0.25746269, 0.30418251])}

In [20]:
cv_knn = cross_validate(knn_model, X_train, Y_train["Encoding"], cv=5)
cv_knn

{'fit_time': array([0.00389194, 0.00292015, 0.00721693, 0.00450993, 0.00293827]),
 'score_time': array([0.01355481, 0.01312399, 0.01733899, 0.0133431 , 0.01072097]),
 'test_score': array([0.17625899, 0.21691176, 0.20817844, 0.19029851, 0.18631179])}

In [21]:
cv_logistic = cross_validate(model, X_train, Y_train["Encoding"], cv=5)
cv_logistic

/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/clairedmedina/opt/a

{'fit_time': array([0.08389497, 0.06725597, 0.07586002, 0.08479381, 0.08005929]),
 'score_time': array([0.00464892, 0.0012238 , 0.00226808, 0.00157905, 0.00158381]),
 'test_score': array([0.30215827, 0.32352941, 0.28624535, 0.28358209, 0.2851711 ])}

In [22]:
cv_clf = cross_validate(clf_model, X_train, Y_train["Encoding"], cv=5)
cv_clf


{'fit_time': array([0.01321292, 0.01329994, 0.01545   , 0.01620889, 0.017699  ]),
 'score_time': array([0.00224304, 0.0033052 , 0.00312901, 0.00203323, 0.00353193]),
 'test_score': array([0.30215827, 0.32352941, 0.30855019, 0.30223881, 0.30418251])}

In [23]:
cv_svm = cross_validate(svm_model, X_train, Y_train["Encoding"], cv=5)
cv_svm

/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/clairedmedin

{'fit_time': array([0.09015083, 0.07659197, 0.07497525, 0.07559013, 0.06861496]),
 'score_time': array([0.0135181 , 0.00962496, 0.0123558 , 0.00998688, 0.01026416]),
 'test_score': array([0.13309353, 0.15073529, 0.133829  , 0.1380597 , 0.14068441])}

<h4> Misclassification rates on the validation sets <h4>

In [24]:
X_val = val[['ft1', 'ft2', 'ft3', 'ft4', 'ft9', 'ft13']]
Y_val = val['Encoding']

In [25]:
clf_pred = clf_model.predict(X_val)
clf_pred

array([ 9, 19, 13, 15, 11,  9, 16, 14,  9, 11, 12, 14, 16, 18,  0,  1,  8,
       16,  9,  0,  2,  9, 19, 14, 17,  0, 19, 11, 10,  2, 11,  2, 10,  8,
        3, 10, 14,  0,  8,  0, 13, 11,  8,  6, 10,  8,  9,  3,  8,  9,  8,
       19, 15, 13,  9, 10,  0,  2, 16, 12, 12,  9,  9,  0, 11,  1,  8, 10,
       10, 13,  9, 10, 10, 19, 13,  9, 14,  9,  8, 12, 16,  0,  3, 16,  9,
        0, 19, 11, 13,  9,  9,  9,  3, 14, 16, 11,  6, 17,  8, 19, 12, 10,
       13,  2, 13,  0,  0, 12,  0, 12,  6, 19, 10,  3, 18,  6, 13, 19, 19,
       14, 12, 16, 10, 14, 10, 19, 10,  9, 10,  6,  8,  0, 15,  9, 18,  0,
       14,  9, 19,  3, 13,  9, 19, 14, 10, 12, 10, 19, 16, 16, 12])

In [26]:
np.mean(clf_pred != Y_val)

0.6821192052980133

In [27]:
logistic_pred = model.predict(X_val)
logistic_pred

array([ 9,  9,  4, 12,  6,  9,  0, 16,  9,  9, 12, 14,  0,  9,  0, 16, 14,
       16,  9,  0,  0,  9,  9, 16, 17,  0, 19,  9,  9, 14,  6, 14,  9, 17,
        3,  9,  2, 14, 14,  9,  9,  6, 14,  6,  9,  9,  9,  3,  2,  9,  9,
        9, 14,  9,  9,  9,  0,  0,  0, 12, 12,  9,  0,  9,  6,  9, 14,  9,
        0,  9, 12,  9,  9, 16,  9,  9, 14, 14,  0, 12, 16,  9,  3,  0,  9,
        0,  9,  6,  0,  9,  9, 12,  3, 16,  0,  6,  6, 16, 14,  9, 12,  9,
        0,  2,  0,  9,  0, 12,  0, 12,  6,  9,  9,  3, 14,  9,  0,  9,  9,
       14, 12, 16,  9, 14,  9,  9,  9,  9,  9,  6,  9,  9,  3, 12,  9,  0,
       14,  9,  9,  3,  0,  9,  9,  3, 16, 12,  9,  9,  0, 12, 12])

In [28]:
np.mean(logistic_pred != Y_val)

0.6622516556291391

In [29]:
knn_pred = knn_model.predict(X_val)
knn_pred

array([ 2,  9,  7,  8, 11,  4, 18,  1,  5,  9, 12,  3, 10,  4,  1, 14,  2,
        1,  6,  0,  5,  9,  5,  1,  3,  9,  7,  8, 10,  5,  1,  1,  0, 17,
        9, 10,  2,  8, 19,  0, 13,  2,  1,  1,  9,  1,  8,  6,  6, 13,  8,
        5,  8,  0,  9,  9,  0,  5,  3, 12, 12,  9,  9, 10,  0, 11,  3,  4,
        0,  9,  1,  7, 13,  7,  0,  2, 14,  8,  0, 12,  2,  4,  6,  0,  9,
       13,  2,  9, 11,  9,  4,  3, 13,  3,  1,  0, 11,  5, 11,  9, 12,  9,
       10,  9,  5,  7,  0, 12, 13, 12, 10,  9,  0,  8,  1,  0,  3,  0,  6,
        7, 12,  9,  0, 14,  2,  2,  0,  2,  0,  5,  5,  0,  1,  1,  1,  2,
        4,  5,  5,  9,  4,  1,  5,  1,  4, 12,  4,  2,  0,  4, 12])

In [30]:
np.mean(knn_pred != Y_val)

0.8079470198675497

In [31]:
rfm_pred = random_forest_model.predict(X_val)
rfm_pred

array([ 9,  8,  6, 17, 11, 15, 17, 17,  3, 15, 12, 13,  5, 18,  0,  8,  7,
       16,  9,  0,  4,  9,  5,  5,  2,  0,  5,  7,  7,  0, 11,  2, 10,  1,
        3,  4,  2,  0,  7,  0, 13,  6, 14,  2,  9,  5,  9,  3, 11,  3,  8,
       15,  9, 13,  9,  9,  0,  2, 16, 12, 12,  8,  7,  0, 11,  1,  7,  9,
       10,  4,  9,  9, 13,  5, 13,  8, 14,  9,  8, 12, 16,  0,  3,  5,  9,
        0,  7, 11,  4,  9,  9,  1,  3, 18, 16,  6,  6,  7,  7,  4, 12, 19,
        1,  2, 13,  0,  0, 12,  0, 12,  6,  9,  9,  3, 18,  6, 10,  5, 15,
        7, 12, 16,  8,  2, 10,  9, 13, 16,  9, 14,  1,  0, 15,  5,  1,  0,
        8,  9,  4,  9, 10,  1,  9,  4, 10, 12,  9, 10,  5,  6, 12])

In [32]:
np.mean(rfm_pred != Y_val)

0.6688741721854304

In [33]:
svm_pred = svm_model.predict(X_val)
svm_pred

array([ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 12,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 12,  9,
        9,  9,  9,  9,  9,  9,  9, 12,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9, 12,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 12])

In [34]:
np.mean(svm_pred != Y_val)

0.8874172185430463

<h4> Image Class Predictions for Test Set <h4>

In [35]:
val_feature_frame = pd.read_pickle('validation_feature_frame.pk1')

In [37]:
val_feature_frame.columns

Index(['Pictures', 'Images', 'ft0', 'ft1', 'ft2', 'ft3', 'ft4', 'ft9', 'ft13',
       'ft14'],
      dtype='object')

In [38]:
X_test = val_feature_frame[['ft1', 'ft2', 'ft3', 'ft4', 'ft9', 'ft13']]

In [44]:
final_pred_encoding = random_forest_model.predict(X_test)

In [42]:
final_pred = val_feature_frame[['Pictures']]

In [45]:
final_pred["Encoding"] = final_pred_encoding

/Users/clairedmedina/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [46]:
final_pred.head()

Pictures  Encoding
0  [[[80, 79, 74], [56, 55, 50], [54, 53, 48], [4...        14
1  [[[10, 15, 19], [10, 15, 19], [11, 16, 19], [1...         0
2  [[[232, 231, 247], [250, 249, 255], [235, 234,...         9
3  [[[97, 75, 77], [98, 76, 78], [99, 77, 79], [1...        11
4  [[[19, 46, 55], [19, 46, 53], [20, 47, 54], [2...         3

In [47]:
export_final_pred = final_pred.to_csv('final_pred.csv', index=None, header=True)